version: '3'
services:
  hotelapi:
    container_name: hotelapi
    build: ./src/TrybeHotel
    ports:
      - 5501:5501
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: database
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TrybeHotel12!
      - MSSQL_PID=Developer